# -*- coding: utf-8 -*-
"""NCKH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uz2Up2ybO6Ms2piwbA0bJRhbXPh3gRi6
"""

#I. Data processing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from google.colab import files
import io

print(">>> Please upload your file")

# 1. Manual File Upload
uploaded = files.upload()

# Check if the file was uploaded
if not uploaded:
    print(">>> No file uploaded. Please run the cell again and select a file.")
else:
    # Get the filename from the upload dictionary
    filename = list(uploaded.keys())[0]
    print(f">>> File '{filename}' uploaded successfully.")

    # 2. Load the raw dataset
    df = pd.read_csv(io.BytesIO(uploaded[filename]))
    print(f">>> Data shape: {df.shape}")

    # 3. Handle Missing Values (Missing Not At Random - MNAR approach)
    # The 'Credit_Product' column has ~12% missing values.
    df['Credit_Product'] = df['Credit_Product'].fillna('Unknown')
    print(">>> Handled missing values in 'Credit_Product' with 'Unknown'.")

    # 4. Separate Target Variable and IDs from the Features
    target = df['Is_Lead']
    ids = df['ID']

    # Drop ID and Target from the feature set
    features_df = df.drop(columns=['ID', 'Is_Lead'])

    # 5. Define Numerical and Categorical columns
    num_cols = ['Age', 'Vintage', 'Avg_Account_Balance']
    cat_cols = ['Gender', 'Region_Code', 'Occupation', 'Channel_Code', 'Credit_Product', 'Is_Active']

    # 6. Feature Scaling (Crucial for distance-based algorithms like K-Prototypes)
    scaler = StandardScaler()
    features_df[num_cols] = scaler.fit_transform(features_df[num_cols])
    print(">>> Numerical features scaled using StandardScaler.")

    # 7. Categorical Encoding (Label Encoding)
    le_dict = {}
    for col in cat_cols:
        le = LabelEncoder()
        features_df[col] = le.fit_transform(features_df[col].astype(str))
        le_dict[col] = le
    print(">>> Categorical features encoded using LabelEncoder.")

    # 8. Final Status
    print("\n>>> [SUCCESS] Data Preprocessing completed!")
    print(">>> Feature DataFrame Preview:")
    display(features_df.head())

#II. K-Prototypes Clurstering
!pip install kmodes
from kmodes.kprototypes import KPrototypes
import time
import pandas as pd

print(">>> [INFO] Adjusting clusters to K=4 to match Bank Classification standards...")

# 1. Identify categorical column indices
cat_cols = ['Gender', 'Region_Code', 'Occupation', 'Channel_Code', 'Credit_Product', 'Is_Active']
cat_col_indices = [features_df.columns.get_loc(col) for col in cat_cols]

# 2. Initialize K-Prototypes with K=4
# k=4 matches the bank's categories (Loyal, Potential, New, Inactive)
kproto = KPrototypes(
    n_clusters=4,
    init='Cao',
    n_init=1,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

print(">>> [INFO] Running clustering on 245,725 records. Please wait...")
start_time = time.time()

# 3. Fit and Predict
clusters = kproto.fit_predict(features_df.values, categorical=cat_col_indices)

duration = (time.time() - start_time) / 60
print(f"\n>>> [SUCCESS] Clustering completed in {duration:.2f} minutes.")

# 4. Merge Cluster Labels back to the original (raw) dataframe for analysis
df_hybrid = df.copy()
df_hybrid['Cluster_Label'] = clusters

# 5. Cluster Profiling
print("\n>>> [ANALYSIS] Cluster Profiles (Mean values):")
profile = df_hybrid.groupby('Cluster_Label').agg({
    'Age': 'mean',
    'Vintage': 'mean',
    'Avg_Account_Balance': 'mean',
    'Is_Lead': 'mean' # This shows the conversion rate per cluster
}).reset_index()

print(profile)

# 6. Save the enhanced dataset
output_file = 'train_hybrid_clustered_v2.csv'
df_hybrid.to_csv(output_file, index=False)
print(f"\n>>> [FILE SAVED] Hybrid dataset saved as '{output_file}'.")

"""DATA PREPARATION"""

!pip install pytorch-tabnet optuna lightgbm catboost -q

import pandas as pd
import numpy as np
import io
import warnings
import optuna
import lightgbm as lgb
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
from pytorch_tabnet.tab_model import TabNetClassifier
from catboost import CatBoostClassifier

warnings.filterwarnings("ignore")

print("[INFO] Awaiting file upload: 'train_hybrid_clustered_v2.csv'")
uploaded = files.upload()

if not uploaded:
    raise FileNotFoundError("[ERROR] File upload failed or was canceled.")

filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]))
print(f"[INFO] Dataset loaded. Shape: {df.shape}")

# Data Preparation
X = df.drop(columns=['ID', 'Is_Lead'])
y = df['Is_Lead']

cat_cols = ['Gender', 'Region_Code', 'Occupation', 'Channel_Code', 'Credit_Product', 'Is_Active', 'Cluster_Label']

for col in cat_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

imbalance_ratio = (y_train == 0).sum() / (y_train == 1).sum()
print(f"[INFO] Class imbalance ratio (scale_pos_weight): {imbalance_ratio:.4f}")


# I. XGBOOST OPTIMIZATION

def objective_xgb(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 500, 1200),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'scale_pos_weight': imbalance_ratio,
        'tree_method': 'hist',
        'random_state': 42,
        'eval_metric': 'auc'
    }

    model = XGBClassifier(**params)
    model.fit(X_train, y_train)
    return roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

print("\n[INFO] Executing XGBoost Optuna tuning...")
study_xgb = optuna.create_study(direction='maximize')
study_xgb.optimize(objective_xgb, n_trials=10)


# II. TABNET OPTIMIZATION

cat_idxs = [i for i, f in enumerate(X.columns) if f in cat_cols]
cat_dims = [X[f].nunique() for f in cat_cols]

def objective_tabnet(trial):
    params = {
        'n_d': trial.suggest_int('n_d', 16, 32),
        'n_a': trial.suggest_int('n_a', 16, 32),
        'n_steps': trial.suggest_int('n_steps', 3, 7),
        'gamma': trial.suggest_float('gamma', 1.2, 1.8),
        'lambda_sparse': trial.suggest_float('lambda_sparse', 1e-4, 1e-3),
        'cat_idxs': cat_idxs,
        'cat_dims': cat_dims,
        'cat_emb_dim': 2,
        'optimizer_params': dict(lr=2e-2),
        'verbose': 0
    }

    model = TabNetClassifier(**params)
    model.fit(
        X_train.values, y_train.values,
        eval_set=[(X_test.values, y_test.values)],
        eval_metric=['auc'],
        max_epochs=10,
        patience=3,
        batch_size=2048,
        virtual_batch_size=256
    )
    return model.best_cost

print("\n[INFO] Executing TabNet Optuna tuning...")
study_tabnet = optuna.create_study(direction='maximize')
study_tabnet.optimize(objective_tabnet, n_trials=5)


# III. LIGHTGBM OPTIMIZATION

def objective_lgbm(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 500, 1500),
        'max_depth': trial.suggest_int('max_depth', 5, 12),
        'num_leaves': trial.suggest_int('num_leaves', 20, 100),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'scale_pos_weight': imbalance_ratio,
        'random_state': 42,
        'metric': 'auc',
        'verbose': -1,
        'n_jobs': -1
    }

    model = lgb.LGBMClassifier(**params)
    model.fit(X_train, y_train)
    return roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

print("\n[INFO] Executing LightGBM Optuna tuning...")
study_lgbm = optuna.create_study(direction='maximize')
study_lgbm.optimize(objective_lgbm, n_trials=10)


# IV. CATBOOST OPTIMIZATION

def objective_catboost(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 500, 1500),
        'depth': trial.suggest_int('depth', 4, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1.0, 10.0),
        'random_strength': trial.suggest_float('random_strength', 0.1, 10.0),
        'scale_pos_weight': imbalance_ratio,
        'random_seed': 42,
        'eval_metric': 'AUC',
        'verbose': False
    }

    model = CatBoostClassifier(**params)
    model.fit(
        X_train, y_train,
        cat_features=cat_cols,
        eval_set=[(X_test, y_test)],
        early_stopping_rounds=50,
        verbose=False
    )
    return roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

print("\n[INFO] Executing CatBoost Optuna tuning...")
study_catboost = optuna.create_study(direction='maximize')
study_catboost.optimize(objective_catboost, n_trials=10)


# FINAL EVALUATION METRICS

print("\n[RESULTS] Final Optimization Metrics (AUC Score):")
print(f"XGBoost  AUC : {study_xgb.best_value:.4f} | Best Params: {study_xgb.best_params}")
print(f"TabNet   AUC : {study_tabnet.best_value:.4f} | Best Params: {study_tabnet.best_params}")
print(f"LightGBM AUC : {study_lgbm.best_value:.4f} | Best Params: {study_lgbm.best_params}")
print(f"CatBoost AUC : {study_catboost.best_value:.4f} | Best Params: {study_catboost.best_params}")

# ==========================================
# FINAL MODEL & XAI VISUALIZATION (CATBOOST)
# ==========================================
import matplotlib.pyplot as plt
from catboost import CatBoostClassifier

print("[INFO] Training Final Champion Model: CatBoost...")

# Best parameters from Optuna tuning
final_catboost_params = {
    'iterations': 779,
    'depth': 6,
    'learning_rate': 0.07195764714272776,
    'l2_leaf_reg': 9.130195215594837,
    'random_strength': 7.534911858590648,
    'scale_pos_weight': imbalance_ratio,
    'random_seed': 42,
    'eval_metric': 'AUC',
    'verbose': False
}

# Train the final model
final_catboost = CatBoostClassifier(**final_catboost_params)
final_catboost.fit(X_train, y_train, cat_features=cat_cols)

# Generate Interpretability Plot
print("[INFO] Generating Feature Importance Plot...")

feature_importances = final_catboost.get_feature_importance()
features = X_train.columns
sorted_idx = feature_importances.argsort()

plt.figure(figsize=(10, 6))
plt.barh(range(len(sorted_idx)), feature_importances[sorted_idx], align='center', color='#1f77b4')
plt.yticks(range(len(sorted_idx)), [features[i] for i in sorted_idx])
plt.xlabel('CatBoost Feature Importance Score')
plt.title('Champion Model: Feature Importance for Lead Scoring')
plt.tight_layout()
plt.show()

print("[SUCCESS] Pipeline completed. Export this plot for your research paper.")